DELETE http://localhost:8080/list/4

###
PUT http://localhost:8080/list/4
Content-Type: application/json

{
  "text": "Bruh"
}

###
POST http://localhost:8080/list
Content-Type: application/json

{
  "text": "Ngangkat Jemuran"
}

###
GET http://localhost:8080
Accept: application/json

###

